[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "open_dataset_store"
version = "1.0.0"
description = "A universal, plug-and-play manager for organising research datasets on Google Drive."
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pandas",
    "fsspec",
    "pydrive2[fsspec]",
    "google-api-python-client"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/janithcyapa/OpenDatasetStore"
"Bug Tracker" = "https://github.com/janithcyapa/OpenDatasetStore/issues"

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"open_dataset_store/__init__.py" = [
    '__version__ = "{version}"',
]
